// src/app/layout.js
import "./globals.css";
import localFont from "next/font/local";
import { Poppins, Playfair_Display } from "next/font/google";

const poppins = Poppins({
  subsets: ["latin"],
  weight: ["400", "700"],
  variable: "--font-poppins",
});

const playfairDisplay = Playfair_Display({
  subsets: ["latin"],
  weight: ["400", "700"],
  variable: "--font-playfair-display",
});

const modernNegra = localFont({
  src: "../fonts/Modern-Negra-Demo.ttf",
  variable: "--font-modern-negra",
});

export const metadata = {
  title: "My Site",
  description: "Generated by Next.js",
};

export default function RootLayout({ children }) {
  return (
    <html
      lang="en"
      className={`${modernNegra.variable} ${poppins.variable} ${playfairDisplay.variable}`}
    >
      <body>{children}</body>
    </html>
  );
}
